name: Build application and deploy to Firebase hosting

on:
  workflow_call:
    inputs:
      projectId:
        required: true
        type: string
    secrets:
      repoToken:
        required: true
      firebaseServiceAccount:
        required: true

jobs:
  build_and_deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies and build application
        run: yarn && yarn build
      - name: Deploy application to Firebase hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.repoToken }}'
          firebaseServiceAccount: '${{ secrets.firebaseServiceAccount }}'
          channelId: live
          projectId: '${{ inputs.projectId }}'