name: Build application and deploy to Firebase hosting

on:
  workflow_call:
    inputs:
      projectId:
        required: true
        type: string
    secrets:
      repoToken:
        required: true
      firebaseServiceAccount:
        required: true

jobs:
  build_and_deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build application
        run: yarn build

      - name: Deploy application to Firebase hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.repoToken }}'
          firebaseServiceAccount: '${{ secrets.firebaseServiceAccount }}'
          channelId: live
          projectId: '${{ inputs.projectId }}'