name: Deploy to production

on:
  push:
    tags:
      - live-*

jobs:
  call-workflow:
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      projectId: kulen-dayz-production
    secrets:
      repoToken: '${{ secrets.GITHUB_TOKEN }}'
      firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KULEN_DAYZ_PRODUCTION }}'