name: Deploy to staging

on:
  push:
    tags:
      - beta-*

jobs:
  call-workflow:
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      projectId: kulen-dayz-staging
    secrets:
      repoToken: '${{ secrets.GITHUB_TOKEN }}'
      firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KULEN_DAYZ_STAGING }}'